=== sigma-hub/sigma-ui/apps/docs/src/public/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "styleSystem": {
      "type": "string",
      "enum": [
        "tailwind",
        "css"
      ]
    },
    "tsConfigPath": {
      "type": "string",
      "default": "./tsconfig.json"
    },
    "setupTailwind": {
      "type": "boolean",
      "default": false
    },
    "framework": {
      "type": "string",
      "enum": [
        "nuxt",
        "vite",
        "laravel",
        "astro"
      ],
      "default": "vite"
    },
    "cssPath": {
      "type": "string"
    },
    "baseColor": {
      "type": "string",
      "default": "slate"
    },
    "tailwind": {
      "type": "object",
      "properties": {
        "config": {
          "type": "string"
        },
        "cssVariables": {
          "type": "boolean",
          "default": true
        },
        "prefix": {
          "type": "string"
        }
      },
      "required": [
        "config"
      ]
    },
    "aliases": {
      "type": "object",
      "properties": {
        "utils": {
          "type": "string",
          "default": ""
        },
        "components": {
          "type": "string"
        }
      },
      "required": [
        "components"
      ]
    },
    "generatePreflight": {
      "type": "boolean",
      "default": true
    }
  },
  "required": [
    "styleSystem",
    "cssPath",
    "baseColor",
    "tailwind",
    "aliases"
  ]
}

=== sigma-hub/sigma-ui/packages/playground-css/sigma-ui.config.json
{
  "$schema": "https://sigma-ui.dev/schema.json",
  "styleSystem": "css",
  "tsConfigPath": "./tsconfig.json",
  "setupTailwind": false,
  "framework": "vite",
  "cssPath": "src/assets/index.css",
  "baseColor": "slate",
  "tailwind": {
    "config": "",
    "cssVariables": true
  },
  "aliases": {
    "utils": "",
    "components": "@/components/ui"
  },
  "generatePreflight": true
}

=== sigma-hub/sigma-ui/packages/playground-tailwind/sigma-ui.config.json
{
  "$schema": "https://sigma-ui.dev/schema.json",
  "styleSystem": "tailwind",
  "tsConfigPath": "./tsconfig.json",
  "setupTailwind": false,
  "framework": "vite",
  "cssPath": "src/assets/index.css",
  "baseColor": "slate",
  "tailwind": {
    "config": "tailwind.config.js",
    "cssVariables": true
  },
  "aliases": {
    "utils": "@/lib/utils",
    "components": "@/components/ui"
  },
  "generatePreflight": true
}

=== sigma-hub/sigma-ui/packages/nuxt-module/playground/sigma-ui.config.json
{
  "$schema": "https://sigma-ui.dev/schema.json",
  "styleSystem": "css",
  "tsConfigPath": "./tsconfig.json",
  "setupTailwind": false,
  "framework": "vite",
  "cssPath": "src/assets/index.css",
  "baseColor": "grayscale",
  "tailwind": {
    "config": ""
  },
  "aliases": {
    "utils": "",
    "components": "@/components"
  },
  "generatePreflight": true
}
